version: '3.8'
services:
  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"

  service-a:
    build: ./ServiceA
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  service-b-data:
    build: ./ServiceB
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  config-server:
    build: ./ConfigServer
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/yourusername/your-config-repo.git
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/